apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: todos.workflows.engine
spec:
  scope: Namespaced
  group: workflows.engine
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRepo:
                  type: string
                gitBranch:
                  type: string
                appName:
                  type: string
                tagName:
                  type: string
                allowedCORS:
                  type: array
                  items:
                    type: string
              required: ["gitRepo"]
  names:
    kind: ToDo
    plural: todos
    singular: todo
    shortNames:
      - todo
  additionalPrinterColumns:
    - name: Git Repo
      type: string
      priority: 0
      JSONPath: .spec.gitRepo
      description: The repo to build the Dockerfile of into an image stream
    - name: Git Branch
      type: string
      priority: 0
      JSONPath: .spec.gitBranch
      description: The git branch to pull (defualt is master)
    - name: appName
      type: string
      priority: 0
      JSONPath: .spec.appName
      description: Name of the resultant app (default is name of ToDO CRD)
    - name: tagName
      type: string
      priority: 0
      JSONPath: .spec.tagName
      description: tag for the image stream  and deploment (default is master)
    - name: CORS
      type: array
      priority: 0
      JSONPath: .spec.allowedCORS
      description: A list of allowed CORS domains (default is "*")
