kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kopf-todo-role-cluster
rules:
  - verbs:
      - list
      - watch
      - patch
      - get
    apiGroups:
      - kopf.dev
    resources:
      - clusterkopfpeerings
  - verbs:
      - list
      - watch
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - namespaces
  - verbs:
      - list
      - watch
      - patch
    apiGroups:
      - workflows.engine
    resources:
      - todos
  - verbs:
      - list
      - create
      - watch
      - patch
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
  - verbs:
      - get
      - create
      - watch
      - patch
    apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
