kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kopf-todo-rolebinding-cluster
subjects:
  - kind: ServiceAccount
    name: kopf-todo-account
    namespace: todo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopf-todo-role-cluster
