apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {STREAM_NAME}
  annotations:
    app.openshift.io/vcs-ref: {GIT_BRANCH}
    app.openshift.io/vcs-uri: "{GIT_REPO}"
  namespace: {NAMESPACE}
  labels:
    app: {APP_NAME}
    app.kubernetes.io/component: {APP_NAME}
    app.kubernetes.io/instance: {APP_NAME}
    app.kubernetes.io/part-of: {APP_NAME}-app
spec:
  lookupPolicy:
    local: false
